# General
set -g default-terminal "tmux-256color"
set -g history-limit 100000
set -g mouse on
set -g escape-time 0
set -g focus-events on

# Better terminal colors
set -as terminal-features ",xterm-256color:RGB"

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf ; display-message "tmux config reloaded"

# Status bar
set -g status on
set -g status-position bottom
set -g status-interval 1
set -g status-justify centre

# Colors
set -g status-style "bg=#111111,fg=#c5c8c6"

# Left
set -g status-left-length 30
set -g status-left "#[fg=#7aa2f7,bold] #S "

# Window tabs
setw -g window-status-format "#[fg=#666666] #I:#W "
setw -g window-status-current-format "#[fg=#111111,bg=#7aa2f7,bold] #I:#W "

# Right
set -g status-right-length 80
set -g status-right "#[fg=#888888]#{pane_current_path} #[fg=#7aa2f7]%H:%M "

# Splits
unbind %
unbind '"'

bind "\\" split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Pane Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Windows
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind c new-window -c "#{pane_current_path}"

bind Tab last-window
bind n next-window
bind p previous-window

# Copy Mode
setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# Performance
set -sg repeat-time 600

# Session
bind-key s choose-tree -Zs

# Plugins
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
